project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!cv/"

website:
  title: "Luiz Henrique"
  description: "Portfólio"
  navbar:
    left:
      - href: index.qmd
        text: Sobre
      # - href: cv.qmd
      #   text: CV
      # - href: portfolio.qmd
      #   text: Portfolio
      - text: Blog
        href: blog.qmd
    right:
      - href: https://www.linkedin.com/in/luiz-henrique-barbosa-filho/
        icon: linkedin
      - href: https://github.com/Vergiel-a
        icon: github
      - href: "mailto:luiz_rique-@hotmail.com"
        icon: envelope-fill
    background: primary
    search: true
    border: true
    background: dark
  site-url: "https://vergiel-a.com"
  repo-url: "https://github.com/Vergiel-a/Vergiel-a.github.io"
  favicon: "images/favl.png"
  open-graph: true

lang: pt
freeze: true

format:
  html:
    author: "Luiz Henrique"
    theme:
      - flatly
    css: styles/css/styles.css
    toc: true
    mainfont: "Lato"
    monofont: "Fira Mono"
    linkcolor: "#3b89bc"
    cap-location: bottom
    page-layout: full
    code-fold: show
    code-overflow: wrap
    code-line-numbers: true
    code-link: true
    code-tools: true
    code-block-bg: "#0d1117"
    highlight-style: oblivion
    freeze: true
    fig-align: center
    fig-width: 8
    fig-height: 4
    fig-asp: 0.618
    fig-dpi: 300
    fig-responsive: true
    link-external-newwindow: true
    link-external-filter: ^(?:http:|https:)\/\/(www\.)?vergiel-a\.com
    footnotes-hover: true
    reference-location: document
